import {
    SiReact,
    SiTypescript,
    SiJavascript,
    SiSass,
    SiCss3,
    SiHtml5,
    SiTailwindcss,
    SiVite,
    SiJest,
    SiTestinglibrary,
    SiGit,
    SiNextdotjs,
    SiNodedotjs,
    SiExpress,
    SiMongodb,
    SiStorybook,
} from 'react-icons/si';

export const techIcons: Record<string, React.ReactNode> = {
    React: <SiReact size={35}/>,
    TypeScript: <SiTypescript size={35}/>,
    Javascript: <SiJavascript size={35}/>,
    SASS: <SiSass size={35}/>,
    CSS: <SiCss3 size={35}/>,
    HTML: <SiHtml5 size={35}/>,
    Tailwind: <SiTailwindcss size={35}/>,
    Vite: <SiVite size={35}/>,
    Jest: <SiJest size={35} />,
    TestingLibrary: <SiTestinglibrary size={35}/>,
    GIT: <SiGit size={35} />,
    Next: <SiNextdotjs size={35} />,
    Node: <SiNodedotjs size={35} />,
    Express: <SiExpress size={35} />,
    Mongodb: <SiMongodb size={35} />,
    Storybook: <SiStorybook size={35} />,
}